"use client"

import type { User, Group, Comment } from "./types"

// Mock data for chapters
export const chapters = [
  { id: "nyc", name: "New York City", memberCount: 1250, image: "/vibrant-nyc-street.png" },
  { id: "sf", name: "San Francisco", memberCount: 980, image: "/golden-gate-vista.png" },
  { id: "la", name: "Los Angeles", memberCount: 1100, image: "/downtown-la-evening.png" },
  { id: "chi", name: "Chicago", memberCount: 850, image: "/chicago-cityscape.png" },
  { id: "bos", name: "Boston", memberCount: 720, image: "/boston-harbor-view.png" },
  { id: "sea", name: "Seattle", memberCount: 680, image: "/Seattle-Skyline-Waterfront.png" },
  { id: "aus", name: "Austin", memberCount: 590, image: "/austin-cityscape-night.png" },
  { id: "den", name: "Denver", memberCount: 510, image: "/denver-cityscape-twilight.png" },
  { id: "por", name: "Portland", memberCount: 470, image: "/portland-cityscape-willamette.png" },
  { id: "boulder", name: "Boulder", memberCount: 350, image: "/boulder-landscape.png" },
]

// Mock data for users
export const mockUsers: User[] = [
  {
    id: "user1",
    name: "Cameron Murdock",
    username: "cameronmurdock",
    email: "cameron.murdock@example.com",
    bio: "Community organizer and event planner",
    avatar: "/cameron-profile.png",
    followers: ["u2", "u3"],
    following: ["u4", "u5"],
    joinedAt: "2023-01-15",
    location: "Boulder, Colorado",
    skills: ["event planning", "community organizing", "fundraising"],
    points: 125,
    chapterTags: ["boulder"],
    groupTags: ["group1", "group2"],
  },
  {
    id: "user2",
    name: "John Smith",
    username: "johnsmith",
    email: "john.smith@example.com",
    bio: "Software engineer and open source contributor",
    avatar: "/abstract-geometric-shapes.png",
    followers: ["u1", "u3", "u4"],
    following: ["u5"],
    joinedAt: "2023-02-20",
    location: "San Francisco, CA",
    skills: ["software development", "web design", "project management"],
    points: 80,
    chapterTags: ["sf"],
    groupTags: ["group2", "group3"],
  },
  {
    id: "user3",
    name: "Jane Doe",
    username: "janedoe",
    email: "jane.doe@example.com",
    bio: "Community organizer and event planner",
    avatar: "/intertwined-letters.png",
    followers: ["u1", "u2", "u5"],
    following: ["u4"],
    joinedAt: "2023-03-10",
    location: "New York, NY",
    skills: ["community organizing", "event planning", "public speaking"],
    points: 150,
    chapterTags: ["nyc"],
    groupTags: ["group1", "group3"],
  },
  {
    id: "user4",
    name: "Alex Johnson",
    username: "alexjohnson",
    email: "alex.johnson@example.com",
    bio: "Graphic designer and marketing specialist",
    avatar: "/abstract-geometric-shapes.png",
    followers: ["u1", "u2", "u3", "u5"],
    following: [],
    joinedAt: "2023-04-05",
    location: "Los Angeles, CA",
    skills: ["graphic design", "marketing", "social media"],
    points: 95,
    chapterTags: ["la"],
    groupTags: ["group2"],
  },
  {
    id: "u5",
    name: "Emily Chen",
    username: "emilychen",
    email: "emily.chen@example.com",
    bio: "Data scientist and policy analyst",
    avatar: "/abstract-geometric-shapes.png",
    followers: ["u1", "u2", "u3", "u4"],
    following: [],
    joinedAt: "2023-05-01",
    location: "Chicago, IL",
    skills: ["data analysis", "policy research", "statistics"],
    points: 110,
    chapterTags: ["chi"],
    groupTags: ["group1"],
  },
]

// Mock data for comments
export const mockComments: Comment[] = [
  // Comments for post1
  {
    id: "comment1",
    postId: "post1",
    author: "user2",
    content: "I'll be there! Looking forward to helping out in the garden.",
    timestamp: "2024-07-15T10:30:00",
    likes: 5,
  },
  {
    id: "comment2",
    postId: "post1",
    author: "user3",
    content: "What should we bring? Do we need any specific tools or equipment?",
    timestamp: "2024-07-15T11:15:00",
    likes: 3,
  },
  {
    id: "comment3",
    postId: "post1",
    author: "user1",
    content:
      "Just bring gloves if you have them! We'll provide all the tools and plants. And don't forget water and sunscreen!",
    timestamp: "2024-07-15T11:45:00",
    likes: 8,
    parentId: "comment2",
  },
  {
    id: "comment4",
    postId: "post1",
    author: "user4",
    content: "Is it okay to bring kids? My daughter loves gardening.",
    timestamp: "2024-07-15T13:20:00",
    likes: 4,
  },
  {
    id: "comment5",
    postId: "post1",
    author: "user1",
    content: "We love having kids join us. There will be some kid-friendly activities too.",
    timestamp: "2024-07-15T14:05:00",
    likes: 6,
    parentId: "comment4",
  },

  // Comments for post2
  {
    id: "comment6",
    postId: "post2",
    author: "user4",
    content: "This sounds amazing! What kind of app are you building?",
    timestamp: "2024-07-14T16:10:00",
    likes: 2,
  },
  {
    id: "comment7",
    postId: "post2",
    author: "user2",
    content:
      "We're building a platform that matches volunteers with local organizations based on skills and interests. It's coming along really well!",
    timestamp: "2024-07-14T16:45:00",
    likes: 7,
    parentId: "comment6",
  },
  {
    id: "comment8",
    postId: "post2",
    author: "user3",
    content: "When will it be available for testing? I'd love to try it out!",
    timestamp: "2024-07-14T17:30:00",
    likes: 3,
    parentId: "comment6",
  },

  // Comments for post3
  {
    id: "comment9",
    postId: "post3",
    author: "user1",
    content: "The food was incredible! Thanks for organizing such a wonderful event.",
    timestamp: "2024-07-13T19:15:00",
    likes: 12,
  },
  {
    id: "comment10",
    postId: "post3",
    author: "user5",
    content: "I loved meeting everyone in the community. These dinners are such a great way to connect!",
    timestamp: "2024-07-13T19:40:00",
    likes: 8,
  },
  {
    id: "comment11",
    postId: "post3",
    author: "user3",
    content: "Thank you all for coming! Our next dinner will be in August - stay tuned for details!",
    timestamp: "2024-07-13T20:15:00",
    likes: 15,
    parentId: "comment10",
  },

  // Comments for other posts
  {
    id: "comment12",
    postId: "post4",
    author: "user3",
    content: "Which workshop did you attend? I've been wanting to learn more about urban farming.",
    timestamp: "2024-07-12T15:00:00",
    likes: 2,
  },
  {
    id: "comment13",
    postId: "post5",
    author: "user2",
    content: "This is so important! Will there be resources for people who can't attend in person?",
    timestamp: "2024-07-11T10:30:00",
    likes: 5,
  },
  {
    id: "comment14",
    postId: "post6",
    author: "user3",
    content: "So proud of everyone who showed up! Our voices are being heard!",
    timestamp: "2024-07-10T18:15:00",
    likes: 20,
  },
  {
    id: "comment15",
    postId: "post7",
    author: "user1",
    content: "I've signed up! Looking forward to collaborating with other developers.",
    timestamp: "2024-07-09T12:30:00",
    likes: 6,
  },
  {
    id: "comment16",
    postId: "post8",
    author: "user5",
    content: "Count me in! Our parks need some love.",
    timestamp: "2024-07-08T14:00:00",
    likes: 4,
  },
  {
    id: "comment17",
    postId: "post9",
    author: "user2",
    content: "This is amazing progress! How can other homeowners get involved?",
    timestamp: "2024-07-07T17:00:00",
    likes: 8,
  },
  {
    id: "comment18",
    postId: "post10",
    author: "user1",
    content: "The artwork was incredible! So much talent in our community.",
    timestamp: "2024-07-06T20:00:00",
    likes: 12,
  },
  {
    id: "comment19",
    postId: "post11",
    author: "user3",
    content: "I'll be there with my fiddle! Can't wait!",
    timestamp: "2024-07-05T15:00:00",
    likes: 5,
  },
  {
    id: "comment20",
    postId: "post12",
    author: "user5",
    content: "Thank you for this important work! How can I volunteer next time?",
    timestamp: "2024-07-04T11:00:00",
    likes: 10,
  },

  // Event comments
  {
    id: "event-comment1",
    eventId: "event1",
    author: "user2",
    content: "This event looks amazing! Can't wait to attend.",
    timestamp: "2023-05-15T14:30:00Z",
    likes: 5,
  },
  {
    id: "event-comment2",
    eventId: "event1",
    author: "user3",
    content: "Will there be a recording for those who can't make it?",
    timestamp: "2023-05-15T15:45:00Z",
    likes: 2,
  },
  {
    id: "event-reply1",
    eventId: "event1",
    author: "user1",
    content: "Yes, we'll share the recording with all registered attendees!",
    timestamp: "2023-05-15T16:20:00Z",
    likes: 3,
    parentId: "event-comment2",
  },
  {
    id: "event-reply2",
    eventId: "event1",
    author: "user4",
    content: "Great! I might not be able to attend live but would love to watch the recording.",
    timestamp: "2023-05-15T17:10:00Z",
    likes: 1,
    parentId: "event-comment2",
  },
  {
    id: "event-comment3",
    eventId: "event2",
    author: "user4",
    content: "Is this event suitable for beginners?",
    timestamp: "2023-05-16T10:15:00Z",
    likes: 1,
  },
  {
    id: "event-reply3",
    eventId: "event2",
    author: "user2",
    content: "We designed it with beginners in mind. No prior experience needed.",
    timestamp: "2023-05-16T11:30:00Z",
    likes: 2,
    parentId: "event-comment3",
  },
  {
    id: "event-comment5",
    eventId: "event1",
    author: "user5",
    content: "I attended last year's event and it was fantastic. Highly recommend!",
    timestamp: "2023-05-18T11:20:00Z",
    likes: 8,
  },
  {
    id: "event-reply4",
    eventId: "event1",
    author: "user2",
    content: "What was your favorite part of last year's event?",
    timestamp: "2023-05-18T12:30:00Z",
    likes: 1,
    parentId: "event-comment5",
  },
  {
    id: "event-reply5",
    eventId: "event1",
    author: "user5",
    content: "Definitely the networking session and the keynote speaker. Both were excellent!",
    timestamp: "2023-05-18T13:45:00Z",
    likes: 3,
    parentId: "event-reply4",
  },
  {
    id: "event-reply6",
    eventId: "event1",
    author: "user1",
    content: "We have an even better keynote speaker this year! You won't want to miss it.",
    timestamp: "2023-05-18T14:20:00Z",
    likes: 4,
    parentId: "event-reply4",
  },
]

// Mock data for groups
export const mockGroups: Group[] = [
  {
    id: "group1",
    name: "Climate Action Coalition",
    description: "Organizing for climate justice and sustainable communities",
    members: ["user1", "user2", "user3"],
    admins: ["user1"],
    adminIds: ["user1"],
    creatorId: "user1",
    avatar: "/global-warming-impacts.png",
    chapterTags: ["nyc", "sf", "chi", "boulder"],
    createdAt: "2023-01-10T12:00:00Z",
    color: "#10b981",
    affiliatedGroups: ["group4", "group8"], // Affiliated with Tech for Social Good and Renewable Energy
  },
  {
    id: "group2",
    name: "Food Justice Network",
    description: "Building equitable food systems and fighting food apartheid",
    members: ["user4", "user5"],
    admins: ["user4"],
    adminIds: ["user4"],
    creatorId: "user4",
    avatar: "/colorful-fruit-display.png",
    chapterTags: ["sf", "por", "sea"],
    createdAt: "2023-02-15T14:30:00Z",
    color: "#f59e0b",
    affiliatedGroups: ["group3", "group5"], // Affiliated with Housing Rights and Urban Farmers
  },
  {
    id: "group3",
    name: "Housing Rights Alliance",
    description: "Fighting for affordable housing and tenant protections",
    members: ["user3"],
    admins: ["user3"],
    adminIds: ["user3"],
    creatorId: "user3",
    avatar: "/diverse-urban-housing.png",
    chapterTags: ["nyc", "la", "chi"],
    createdAt: "2023-03-20T09:15:00Z",
    color: "#3b82f6",
    affiliatedGroups: ["group2", "group7"], // Affiliated with Food Justice and Mutual Aid
  },
  {
    id: "group4",
    name: "Tech for Social Good",
    description: "Using technology to address community challenges",
    members: ["user1", "user2"],
    admins: ["user2"],
    adminIds: ["user2"],
    creatorId: "user2",
    avatar: "/coding-collaboration.png",
    chapterTags: ["sf", "sea", "aus"],
    createdAt: "2023-04-05T16:45:00Z",
    color: "#8b5cf6",
    affiliatedGroups: ["group1", "group6"], // Affiliated with Climate Action and Community Arts
  },
  {
    id: "group5",
    name: "Urban Farmers Collective",
    description: "Growing food and building community in urban spaces",
    members: ["user3", "user4"],
    admins: ["user3"],
    adminIds: ["user3"],
    creatorId: "user3",
    avatar: "/vibrant-urban-garden.png",
    chapterTags: ["nyc", "chi", "por"],
    createdAt: "2023-05-12T11:20:00Z",
    color: "#65a30d",
    affiliatedGroups: ["group2", "group9"], // Affiliated with Food Justice and Riverside Events
  },
  {
    id: "group6",
    name: "Community Arts Initiative",
    description: "Supporting local artists and community-based arts",
    members: ["user5"],
    admins: ["user5"],
    adminIds: ["user5"],
    creatorId: "user5",
    avatar: "/vibrant-city-art-fair.png",
    chapterTags: ["la", "aus", "den"],
    createdAt: "2023-06-18T13:10:00Z",
    color: "#ec4899",
    affiliatedGroups: ["group4", "group9"], // Affiliated with Tech for Social Good and Riverside Events
  },
  {
    id: "group7",
    name: "Mutual Aid Network",
    description: "Neighbors helping neighbors through direct community support",
    members: ["user1", "user3", "user5"],
    admins: ["user1"],
    adminIds: ["user1"],
    creatorId: "user1",
    avatar: "/hands-helping-grow.png",
    chapterTags: ["bos", "nyc", "chi"],
    createdAt: "2023-07-22T10:30:00Z",
    color: "#ef4444",
    affiliatedGroups: ["group3", "group8"], // Affiliated with Housing Rights and Renewable Energy
  },
  {
    id: "group8",
    name: "Renewable Energy Cooperative",
    description: "Community-owned clean energy projects",
    members: ["user2", "user4"],
    admins: ["user4"],
    adminIds: ["user4"],
    creatorId: "user4",
    avatar: "/renewable-energy.png",
    chapterTags: ["den", "boulder", "por"],
    createdAt: "2023-08-30T15:45:00Z",
    color: "#0ea5e9",
    affiliatedGroups: ["group1", "group7"], // Affiliated with Climate Action and Mutual Aid
  },
  {
    id: "group9",
    name: "Riverside Events Venue",
    description: "A beautiful riverside venue for community gatherings, performances, and events in Boulder",
    members: ["user1"],
    admins: ["user1"],
    adminIds: ["user1"],
    creatorId: "user1",
    avatar: "/boulder-landscape.png",
    chapterTags: ["boulder"],
    location: {
      city: "Boulder, CO",
      lat: 40.015,
      lng: -105.2705,
    },
    createdAt: "2023-09-14T09:00:00Z",
    color: "#0d9488",
    affiliatedGroups: ["group5", "group6"], // Affiliated with Urban Farmers and Community Arts
  },
]

// Mock data for subgroups
export const mockSubgroups: Group[] = [
  // Climate Action Coalition subgroups
  {
    id: "subgroup1",
    name: "Youth Climate Activists",
    description: "Young people organizing for climate justice and policy change",
    members: ["user1", "user3"],
    admins: ["user1"],
    adminIds: ["user1"],
    creatorId: "user1",
    avatar: "/hands-of-solidarity.png",
    chapterTags: ["nyc", "sf"],
    parentGroupId: "group1",
    createdAt: "2023-01-25T14:30:00Z",
    color: "#10b981",
  },
  {
    id: "subgroup2",
    name: "Climate Policy Team",
    description: "Focused on policy advocacy and legislative change for climate action",
    members: ["user2", "user3"],
    admins: ["user3"],
    adminIds: ["user3"],
    creatorId: "user3",
    avatar: "/global-warming-impacts.png",
    chapterTags: ["chi", "boulder"],
    parentGroupId: "group1",
    createdAt: "2023-02-10T11:15:00Z",
    color: "#10b981",
  },

  // Food Justice Network subgroups
  {
    id: "subgroup3",
    name: "Community Gardens Initiative",
    description: "Creating and supporting community gardens in urban neighborhoods",
    members: ["user4"],
    admins: ["user4"],
    adminIds: ["user4"],
    creatorId: "user4",
    avatar: "/vibrant-garden-tending.png",
    chapterTags: ["sf", "por"],
    parentGroupId: "group2",
    createdAt: "2023-03-05T09:45:00Z",
    color: "#f59e0b",
  },
  {
    id: "subgroup4",
    name: "Food Distribution Network",
    description: "Coordinating food distribution to communities in need",
    members: ["user4", "user5"],
    admins: ["user4"],
    adminIds: ["user4"],
    creatorId: "user4",
    avatar: "/colorful-fruit-display.png",
    chapterTags: ["sea"],
    parentGroupId: "group2",
    createdAt: "2023-04-12T13:20:00Z",
    color: "#f59e0b",
  },

  // Housing Rights Alliance subgroups
  {
    id: "subgroup5",
    name: "Tenant Organizing Committee",
    description: "Supporting tenants to organize for better housing conditions",
    members: ["user3"],
    admins: ["user3"],
    adminIds: ["user3"],
    creatorId: "user3",
    avatar: "/diverse-urban-housing.png",
    chapterTags: ["nyc", "chi"],
    parentGroupId: "group3",
    createdAt: "2023-05-18T10:30:00Z",
    color: "#3b82f6",
  },
  {
    id: "subgroup6",
    name: "Housing Policy Advocates",
    description: "Working on policy solutions for affordable housing",
    members: ["user3"],
    admins: ["user3"],
    adminIds: ["user3"],
    creatorId: "user3",
    avatar: "/diverse-urban-housing.png",
    chapterTags: ["la"],
    parentGroupId: "group3",
    createdAt: "2023-06-22T15:45:00Z",
    color: "#3b82f6",
  },

  // Tech for Social Good subgroups
  {
    id: "subgroup7",
    name: "Civic Tech Developers",
    description: "Building technology solutions for civic challenges",
    members: ["user1", "user2"],
    admins: ["user2"],
    adminIds: ["user2"],
    creatorId: "user2",
    avatar: "/coding-collaboration.png",
    chapterTags: ["sf"],
    parentGroupId: "group4",
    createdAt: "2023-07-10T11:00:00Z",
    color: "#8b5cf6",
  },
  {
    id: "subgroup8",
    name: "Digital Inclusion Team",
    description: "Working to bridge the digital divide in underserved communities",
    members: ["user2"],
    admins: ["user2"],
    adminIds: ["user2"],
    creatorId: "user2",
    avatar: "/dev-team.png",
    chapterTags: ["sea", "aus"],
    parentGroupId: "group4",
    createdAt: "2023-08-15T14:30:00Z",
    color: "#8b5cf6",
  },

  // Urban Farmers Collective subgroups
  {
    id: "subgroup9",
    name: "Rooftop Gardens Project",
    description: "Creating food-producing gardens on urban rooftops",
    members: ["user3"],
    admins: ["user3"],
    adminIds: ["user3"],
    creatorId: "user3",
    avatar: "/vibrant-urban-garden.png",
    chapterTags: ["nyc"],
    parentGroupId: "group5",
    createdAt: "2023-09-05T09:15:00Z",
    color: "#65a30d",
  },
  {
    id: "subgroup10",
    name: "Urban Farming Education",
    description: "Teaching urban farming techniques to community members",
    members: ["user3", "user4"],
    admins: ["user3"],
    adminIds: ["user3"],
    creatorId: "user3",
    avatar: "/community-agriculture.png",
    chapterTags: ["chi", "por"],
    parentGroupId: "group5",
    createdAt: "2023-10-12T13:45:00Z",
    color: "#65a30d",
  },

  // Community Arts Initiative subgroups
  {
    id: "subgroup11",
    name: "Public Art Collective",
    description: "Creating public art installations in urban spaces",
    members: ["user5"],
    admins: ["user5"],
    adminIds: ["user5"],
    creatorId: "user5",
    avatar: "/vibrant-city-art-fair.png",
    chapterTags: ["la", "aus"],
    parentGroupId: "group6",
    createdAt: "2023-11-08T11:30:00Z",
    color: "#ec4899",
  },
  {
    id: "subgroup12",
    name: "Community Theater Group",
    description: "Producing theater that addresses social issues",
    members: ["user5"],
    admins: ["user5"],
    adminIds: ["user5"],
    creatorId: "user5",
    avatar: "/vibrant-stage-energy.png",
    chapterTags: ["den"],
    parentGroupId: "group6",
    createdAt: "2023-12-15T16:00:00Z",
    color: "#ec4899",
  },

  // Mutual Aid Network subgroups
  {
    id: "subgroup13",
    name: "Food Security Team",
    description: "Ensuring food access for vulnerable community members",
    members: ["user1", "user5"],
    admins: ["user1"],
    adminIds: ["user1"],
    creatorId: "user1",
    avatar: "/hands-helping-grow.png",
    chapterTags: ["bos", "nyc"],
    parentGroupId: "group7",
    createdAt: "2024-01-10T10:15:00Z",
    color: "#ef4444",
  },
  {
    id: "subgroup14",
    name: "Resource Distribution Network",
    description: "Coordinating distribution of essential resources",
    members: ["user3", "user5"],
    admins: ["user3"],
    adminIds: ["user3"],
    creatorId: "user3",
    avatar: "/equitable-resource-flow.png",
    chapterTags: ["chi"],
    parentGroupId: "group7",
    createdAt: "2024-02-18T14:30:00Z",
    color: "#ef4444",
  },

  // Renewable Energy Cooperative subgroups
  {
    id: "subgroup15",
    name: "Solar Installation Team",
    description: "Installing solar panels on community buildings",
    members: ["user2", "user4"],
    admins: ["user4"],
    adminIds: ["user4"],
    creatorId: "user4",
    avatar: "/renewable-energy.png",
    chapterTags: ["den", "boulder"],
    parentGroupId: "group8",
    createdAt: "2024-03-05T09:45:00Z",
    color: "#0ea5e9",
  },
  {
    id: "subgroup16",
    name: "Energy Policy Advocates",
    description: "Advocating for renewable energy policies",
    members: ["user2"],
    admins: ["user2"],
    adminIds: ["user2"],
    creatorId: "user2",
    avatar: "/renewable-energy.png",
    chapterTags: ["por"],
    parentGroupId: "group8",
    createdAt: "2024-04-12T11:30:00Z",
    color: "#0ea5e9",
  },

  // Riverside Events Venue subgroups
  {
    id: "subgroup17",
    name: "Event Planning Committee",
    description: "Planning and coordinating events at the Riverside venue",
    members: ["user1"],
    admins: ["user1"],
    adminIds: ["user1"],
    creatorId: "user1",
    avatar: "/boulder-landscape.png",
    chapterTags: ["boulder"],
    parentGroupId: "group9",
    createdAt: "2024-05-08T13:15:00Z",
    color: "#0d9488",
  },
  {
    id: "subgroup18",
    name: "Venue Maintenance Team",
    description: "Maintaining and improving the Riverside venue facilities",
    members: ["user1"],
    admins: ["user1"],
    adminIds: ["user1"],
    creatorId: "user1",
    avatar: "/boulder-landscape.png",
    chapterTags: ["boulder"],
    parentGroupId: "group9",
    createdAt: "2024-06-15T10:30:00Z",
    color: "#0d9488",
  },
]

// Combine groups and subgroups for the full list
export const allGroups = [...mockGroups, ...mockSubgroups]

// Mock projects/events data
export const mockEvents = [
  {
    id: "event1",
    name: "Community Garden Workday",
    description: "Monthly workday to maintain our community garden",
    location: {
      address: "123 Garden St, Boulder, CO",
    },
    organizer: "group1",
    groupId: "group1",
    image: "/vibrant-garden-tending.png",
    chapterTags: ["boulder"],
    type: "event",
    timeframe: {
      start: "2024-07-20T10:00:00",
      end: "2024-07-20T14:00:00",
    },
    price: 0,
    admins: ["user1", "user3"],
    creatorId: "user1",
  },
  {
    id: "event2",
    name: "Tech Workshop Series",
    description: "Learn coding and digital skills for community organizing",
    location: {
      address: "456 Tech Ave, San Francisco, CA",
    },
    organizer: "group4",
    groupId: "group4",
    image: "/coding-collaboration.png",
    chapterTags: ["sf"],
    type: "event",
    timeframe: {
      start: "2024-08-05T18:00:00",
      end: "2024-08-05T20:00:00",
    },
    price: 15,
    admins: ["user2"],
    creatorId: "user2",
  },
  {
    id: "event3",
    name: "Community Dinner",
    description: "Free community meal with locally sourced ingredients",
    location: {
      address: "789 Food St, Los Angeles, CA",
    },
    organizer: "group2",
    groupId: "group2",
    image: "/neighborhood-gathering.png",
    chapterTags: ["la"],
    type: "event",
    timeframe: {
      start: "2024-08-15T17:00:00",
      end: "2024-08-15T19:00:00",
    },
    price: 0,
    admins: ["user3"],
    creatorId: "user3",
  },
  {
    id: "event4",
    name: "Climate Action Rally",
    description: "Join us to demand climate justice and policy action",
    location: {
      address: "City Hall, New York, NY",
    },
    organizer: "group1",
    groupId: "group1",
    image: "/hands-of-solidarity.png",
    chapterTags: ["nyc"],
    type: "event",
    timeframe: {
      start: "2024-07-25T12:00:00",
      end: "2024-07-25T15:00:00",
    },
    price: 0,
    admins: ["user1", "user5"],
    creatorId: "user1",
  },
  {
    id: "event5",
    name: "Urban Farming Workshop",
    description: "Learn techniques for growing food in urban environments",
    location: {
      address: "Community Center, Chicago, IL",
    },
    organizer: "group5",
    groupId: "group5",
    image: "/community-agriculture.png",
    chapterTags: ["chi"],
    type: "event",
    timeframe: {
      start: "2024-08-10T10:00:00",
      end: "2024-08-10T13:00:00",
    },
    price: 10,
    admins: ["user4"],
    creatorId: "user4",
  },
  {
    id: "event6",
    name: "Housing Rights Workshop",
    description: "Learn about tenant rights and housing advocacy",
    location: {
      address: "Public Library, Seattle, WA",
    },
    organizer: "group3",
    groupId: "group3",
    image: "/diverse-urban-housing.png",
    chapterTags: ["sea"],
    type: "event",
    timeframe: {
      start: "2024-08-20T18:00:00",
      end: "2024-08-20T20:00:00",
    },
    price: 0,
    admins: ["user3"],
    creatorId: "user3",
  },
  {
    id: "event7",
    name: "Community Art Festival",
    description: "Celebrating local artists and community creativity",
    location: {
      address: "Central Park, Austin, TX",
    },
    organizer: "group6",
    groupId: "group6",
    image: "/vibrant-city-art-fair.png",
    chapterTags: ["aus"],
    type: "event",
    timeframe: {
      start: "2024-09-05T11:00:00",
      end: "2024-09-05T18:00:00",
    },
    price: 5,
    admins: ["user1", "user5"],
    creatorId: "user5",
  },
  {
    id: "event8",
    name: "Renewable Energy Forum",
    description: "Discussion on community-owned renewable energy projects",
    location: {
      address: "Convention Center, Denver, CO",
    },
    organizer: "group8",
    groupId: "group8",
    image: "/renewable-energy.png",
    chapterTags: ["den"],
    type: "event",
    timeframe: {
      start: "2024-09-15T14:00:00",
      end: "2024-09-15T17:00:00",
    },
    price: 20,
    admins: ["user4"],
    creatorId: "user4",
  },
  {
    id: "event9",
    name: "Community Cleanup Day",
    description: "Join us to clean up our neighborhood parks and streets",
    location: {
      address: "Riverside Park, Portland, OR",
    },
    organizer: "group1",
    groupId: "group1",
    image: "/community-park-cleanup.png",
    chapterTags: ["por"],
    type: "event",
    timeframe: {
      start: "2024-09-25T09:00:00",
      end: "2024-09-25T12:00:00",
    },
    price: 0,
    admins: ["user3"],
    creatorId: "user3",
  },
  {
    id: "event10",
    name: "Irish Music Session",
    description: "Traditional Irish music jam session - all welcome!",
    location: {
      address: "O'Malley's Pub, Boston, MA",
    },
    organizer: "group7",
    groupId: "group7",
    image: "/lively-irish-session.png",
    chapterTags: ["bos"],
    type: "event",
    timeframe: {
      start: "2024-07-22T19:00:00",
      end: "2024-07-22T22:00:00",
    },
    price: 5,
    admins: ["user1"],
    creatorId: "user1",
  },
  {
    id: "event11",
    name: "Tech for Good Hackathon",
    description: "Building tech solutions for local community challenges",
    location: {
      address: "Tech Hub, San Francisco, CA",
    },
    organizer: "group4",
    groupId: "group4",
    image: "/dev-team.png",
    chapterTags: ["sf"],
    type: "event",
    timeframe: {
      start: "2024-08-12T09:00:00",
      end: "2024-08-13T17:00:00",
    },
    price: 25,
    admins: ["user2"],
    creatorId: "user2",
  },
  {
    id: "event12",
    name: "Community Potluck",
    description: "Bring a dish to share and meet your neighbors",
    location: {
      address: "Community Center, Boulder, CO",
    },
    organizer: "group9",
    groupId: "group9",
    image: "/hearty-irish-spread.png",
    chapterTags: ["boulder"],
    type: "event",
    timeframe: {
      start: "2024-07-28T17:00:00",
      end: "2024-07-28T20:00:00",
    },
    price: 0,
    admins: ["user3"],
    creatorId: "user3",
  },
  // Additional events for groups
  {
    id: "event13",
    name: "Monthly Climate Action Meeting",
    description: "Strategic planning meeting for our climate initiatives",
    location: {
      address: "Community Center, Boulder, CO",
    },
    organizer: "group1",
    groupId: "group1",
    image: "/global-warming-impacts.png",
    chapterTags: ["boulder"],
    type: "event",
    timeframe: {
      start: "2024-07-18T18:00:00",
      end: "2024-07-18T20:00:00",
    },
    price: 0,
    admins: ["user1"],
    creatorId: "user1",
  },
  {
    id: "event14",
    name: "Food Justice Panel Discussion",
    description: "Experts discuss equitable food systems and community solutions",
    location: {
      address: "Public Library, San Francisco, CA",
    },
    organizer: "group2",
    groupId: "group2",
    image: "/colorful-fruit-display.png",
    chapterTags: ["sf"],
    type: "event",
    timeframe: {
      start: "2024-07-22T17:30:00",
      end: "2024-07-22T19:30:00",
    },
    price: 0,
    admins: ["user4"],
    creatorId: "user4",
  },
  {
    id: "event15",
    name: "Tenant Rights Workshop",
    description: "Learn about your rights as a tenant and how to organize",
    location: {
      address: "Community Center, New York, NY",
    },
    organizer: "group3",
    groupId: "group3",
    image: "/diverse-urban-housing.png",
    chapterTags: ["nyc"],
    type: "event",
    timeframe: {
      start: "2024-07-25T18:00:00",
      end: "2024-07-25T20:00:00",
    },
    price: 0,
    admins: ["user3"],
    creatorId: "user3",
  },
  {
    id: "event16",
    name: "Coding for Beginners Workshop",
    description: "Introduction to coding for community organizers",
    location: {
      address: "Tech Hub, Seattle, WA",
    },
    organizer: "group4",
    groupId: "group4",
    image: "/coding-collaboration.png",
    chapterTags: ["sea"],
    type: "event",
    timeframe: {
      start: "2024-07-29T17:00:00",
      end: "2024-07-29T19:00:00",
    },
    price: 10,
    admins: ["user2"],
    creatorId: "user2",
  },
  {
    id: "event17",
    name: "Urban Gardening Basics",
    description: "Learn how to start growing food in urban environments",
    location: {
      address: "Community Garden, Chicago, IL",
    },
    organizer: "group5",
    groupId: "group5",
    image: "/vibrant-urban-garden.png",
    chapterTags: ["chi"],
    type: "event",
    timeframe: {
      start: "2024-08-02T10:00:00",
      end: "2024-08-02T12:00:00",
    },
    price: 5,
    admins: ["user3"],
    creatorId: "user3",
  },
  {
    id: "event18",
    name: "Community Art Exhibition",
    description: "Showcasing works by local artists addressing social issues",
    location: {
      address: "Art Gallery, Austin, TX",
    },
    organizer: "group6",
    groupId: "group6",
    image: "/vibrant-city-art-fair.png",
    chapterTags: ["aus"],
    type: "event",
    timeframe: {
      start: "2024-08-05T18:00:00",
      end: "2024-08-05T21:00:00",
    },
    price: 0,
    admins: ["user5"],
    creatorId: "user5",
  },
  {
    id: "event19",
    name: "Mutual Aid Network Training",
    description: "Learn how to organize mutual aid in your neighborhood",
    location: {
      address: "Community Center, Boston, MA",
    },
    organizer: "group7",
    groupId: "group7",
    image: "/hands-helping-grow.png",
    chapterTags: ["bos"],
    type: "event",
    timeframe: {
      start: "2024-08-08T18:00:00",
      end: "2024-08-08T20:00:00",
    },
    price: 0,
    admins: ["user1"],
    creatorId: "user1",
  },
  {
    id: "event20",
    name: "Solar Panel Installation Workshop",
    description: "Hands-on training for community solar installations",
    location: {
      address: "Community Center, Denver, CO",
    },
    organizer: "group8",
    groupId: "group8",
    image: "/renewable-energy.png",
    chapterTags: ["den"],
    type: "event",
    timeframe: {
      start: "2024-08-12T09:00:00",
      end: "2024-08-12T16:00:00",
    },
    price: 15,
    admins: ["user4"],
    creatorId: "user4",
  },
  {
    id: "event21",
    name: "Riverside Summer Concert",
    description: "Live music by local bands at our beautiful riverside venue",
    location: {
      address: "Riverside Events Venue, Boulder, CO",
    },
    organizer: "group9",
    groupId: "group9",
    image: "/vibrant-stage-energy.png",
    chapterTags: ["boulder"],
    type: "event",
    timeframe: {
      start: "2024-08-15T17:00:00",
      end: "2024-08-15T22:00:00",
    },
    price: 10,
    admins: ["user1"],
    creatorId: "user1",
  },
]

// Export for backward compatibility
export const users = mockUsers
export const groups = allGroups
export const projects = mockEvents
export const comments = mockComments

// Mock data for group relationships
export const groupRelationships = [
  {
    sourceGroupId: "group1",
    targetGroupId: "group2",
    type: "affiliate",
    description: "Working together on climate and tech initiatives",
    createdAt: "2023-05-01",
    createdBy: "u1",
  },
  {
    sourceGroupId: "group2",
    targetGroupId: "group3",
    type: "partner",
    description: "Partnering on food and housing projects",
    createdAt: "2023-06-10",
    createdBy: "u4",
  },
  {
    sourceGroupId: "group4",
    targetGroupId: "group1",
    type: "coalition",
    description: "Joining forces for community resilience",
    createdAt: "2023-07-01",
    createdBy: "u5",
  },
]

// Mock data for job shifts
export const jobShifts = [
  {
    id: "shift1",
    name: "Garden Maintenance",
    project: "p1",
    timeframe: {
      start: "2024-07-20T10:00:00",
      end: "2024-07-20T14:00:00",
    },
    assignedUsers: ["u1", "u2"],
  },
  {
    id: "shift2",
    name: "Coding Workshop Instructor",
    project: "p2",
    timeframe: {
      start: "2024-08-05T18:00:00",
      end: "2024-08-05T20:00:00",
    },
    assignedUsers: ["u4"],
  },
  {
    id: "shift3",
    name: "Community Dinner Chef",
    project: "p3",
    timeframe: {
      start: "2024-08-15T17:00:00",
      end: "2024-08-15T19:00:00",
    },
    assignedUsers: ["u3"],
  },
  {
    id: "shift4",
    name: "Climate Rally Setup",
    project: "event4",
    timeframe: {
      start: "2024-07-25T09:00:00",
      end: "2024-07-25T11:30:00",
    },
    assignedUsers: ["u1", "u5"],
  },
  {
    id: "shift5",
    name: "Climate Rally Cleanup",
    project: "event4",
    timeframe: {
      start: "2024-07-25T15:00:00",
      end: "2024-07-25T17:00:00",
    },
    assignedUsers: ["u2", "u3"],
  },
  {
    id: "shift6",
    name: "Urban Farming Instructor",
    project: "event5",
    timeframe: {
      start: "2024-08-10T10:00:00",
      end: "2024-08-10T13:00:00",
    },
    assignedUsers: ["u4"],
  },
  {
    id: "shift7",
    name: "Housing Workshop Facilitator",
    project: "event6",
    timeframe: {
      start: "2024-08-20T17:30:00",
      end: "2024-08-20T20:30:00",
    },
    assignedUsers: ["u3"],
  },
  {
    id: "shift8",
    name: "Art Festival Setup",
    project: "event7",
    timeframe: {
      start: "2024-09-05T08:00:00",
      end: "2024-09-05T10:30:00",
    },
    assignedUsers: ["u5", "u1"],
  },
  {
    id: "shift9",
    name: "Art Festival Booth",
    project: "event7",
    timeframe: {
      start: "2024-09-05T11:00:00",
      end: "2024-09-05T15:00:00",
    },
    assignedUsers: ["u2"],
  },
  {
    id: "shift10",
    name: "Art Festival Cleanup",
    project: "event7",
    timeframe: {
      start: "2024-09-05T18:00:00",
      end: "2024-09-05T20:00:00",
    },
    assignedUsers: ["u3", "u4"],
  },
]

// Mock data for thanks
export const thanks = [
  {
    id: "t1",
    from: "u2",
    to: "u1",
    message: "Thanks for organizing the community garden workday!",
    points: 10,
    date: "2024-07-16T09:00:00",
  },
  {
    id: "t2",
    from: "u4",
    to: "u3",
    message: "Thank you for leading the tech workshop series!",
    points: 15,
    date: "2024-07-17T14:00:00",
  },
  {
    id: "t3",
    from: "u5",
    to: "u1",
    message: "Thanks for all your hard work on the community dinner!",
    points: 20,
    date: "2024-07-18T16:00:00",
  },
]

// Mock data for posts
export const posts = [
  {
    id: "post1",
    author: "user1",
    content:
      "Excited to announce our upcoming community garden workday! Join us this Saturday to help plant new vegetables and flowers.",
    images: ["/vibrant-garden-tending.png"],
    timestamp: "2024-07-15T10:00:00",
    likes: 42,
    comments: 12,
    chapterTags: ["boulder"],
    groupTags: ["group1"],
    groupId: "group1",
  },
  {
    id: "post2",
    author: "user2",
    content:
      "Just finished a great coding session with the Tech for Good group. We're building a new app to connect volunteers with local organizations.",
    images: ["/coding-collaboration.png"],
    timestamp: "2024-07-14T15:30:00",
    likes: 35,
    comments: 8,
    chapterTags: ["sf"],
    groupTags: ["group4"],
    groupId: "group4",
  },
  {
    id: "post3",
    author: "user3",
    content: "Our community dinner was a huge success! Thanks to everyone who came out and shared a meal with us.",
    images: ["/neighborhood-gathering.png"],
    timestamp: "2024-07-13T18:45:00",
    likes: 58,
    comments: 20,
    chapterTags: ["la"],
    groupTags: ["group2"],
    groupId: "group2",
  },
  {
    id: "post4",
    author: "user4",
    content:
      "Just attended an amazing workshop on urban farming techniques. Can't wait to apply what I learned to our community garden!",
    images: ["/community-agriculture.png"],
    timestamp: "2024-07-12T14:20:00",
    likes: 27,
    comments: 5,
    chapterTags: ["chi"],
    groupTags: ["group5"],
    groupId: "group5",
  },
  {
    id: "post5",
    author: "user5",
    content:
      "Our housing rights workshop is coming up next week. Learn about tenant protections and how to advocate for affordable housing!",
    images: ["/diverse-urban-housing.png"],
    timestamp: "2024-07-11T09:15:00",
    likes: 31,
    comments: 7,
    chapterTags: ["nyc"],
    groupTags: ["group3"],
    groupId: "group3",
  },
  {
    id: "post6",
    author: "user1",
    content: "The climate action rally was a huge success! Over 500 people showed up to demand climate justice.",
    images: ["/hands-of-solidarity.png"],
    timestamp: "2024-07-10T17:30:00",
    likes: 89,
    comments: 23,
    chapterTags: ["nyc"],
    groupTags: ["group1"],
    groupId: "group1",
  },
  {
    id: "post7",
    author: "user2",
    content: "Our tech hackathon is coming up! Join us to build solutions for local community challenges.",
    images: ["/dev-team.png"],
    timestamp: "2024-07-09T11:45:00",
    likes: 42,
    comments: 15,
    chapterTags: ["sf"],
    groupTags: ["group4"],
    groupId: "group4",
  },
  {
    id: "post8",
    author: "user3",
    content: "Community cleanup day this weekend! Bring gloves and join us to clean up our neighborhood parks.",
    images: ["/community-park-cleanup.png"],
    timestamp: "2024-07-08T13:20:00",
    likes: 36,
    comments: 9,
    chapterTags: ["por"],
    groupTags: ["group1"],
    groupId: "group1",
  },
  {
    id: "post9",
    author: "user4",
    content:
      "Our renewable energy cooperative just installed solar panels on its 50th home! Moving toward community-owned clean energy.",
    images: ["/renewable-energy.png"],
    timestamp: "2024-07-07T16:10:00",
    likes: 67,
    comments: 14,
    chapterTags: ["den"],
    groupTags: ["group8"],
    groupId: "group8",
  },
  {
    id: "post10",
    author: "user5",
    content: "The community arts festival was amazing! So much local talent on display.",
    images: ["/vibrant-city-art-fair.png"],
    timestamp: "2024-07-06T19:25:00",
    likes: 73,
    comments: 18,
    chapterTags: ["aus"],
    groupTags: ["group6"],
    groupId: "group6",
  },
  {
    id: "post11",
    author: "user1",
    content:
      "Traditional Irish music session tonight at O'Malley's! All musicians welcome, or just come to listen and enjoy.",
    images: ["/lively-irish-session.png"],
    timestamp: "2024-07-05T14:30:00",
    likes: 29,
    comments: 6,
    chapterTags: ["bos"],
    groupTags: ["group7"],
    groupId: "group7",
  },
  {
    id: "post12",
    author: "user2",
    content: "Our mutual aid network distributed food to 100 families this week. Thanks to all our volunteers!",
    images: ["/hands-helping-grow.png"],
    timestamp: "2024-07-04T10:15:00",
    likes: 84,
    comments: 21,
    chapterTags: ["chi"],
    groupTags: ["group7"],
    groupId: "group7",
  },
]
